# Railway Configuration - Bypass Docker Hub outage
# Using Nixpacks instead of Dockerfile during Docker Hub downtime

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

