-- ============================================================================
-- SERVICE LINE BLUEPRINTS
-- Complete service line definitions generated by the Service Line Builder
-- ============================================================================

CREATE TABLE IF NOT EXISTS service_line_blueprints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  practice_id UUID NOT NULL REFERENCES practices(id) ON DELETE CASCADE,

  -- Source tracking
  source_type TEXT NOT NULL DEFAULT 'manual'
    CHECK (source_type IN ('concept', 'opportunity', 'manual', 'clone')),
  source_concept_id UUID REFERENCES service_concepts(id) ON DELETE SET NULL,
  source_opportunity_id UUID REFERENCES discovery_opportunities(id) ON DELETE SET NULL,

  -- Workflow
  status TEXT NOT NULL DEFAULT 'generating'
    CHECK (status IN (
      'generating',
      'draft',
      'reviewed',
      'approved',
      'implemented',
      'archived'
    )),

  -- Identity
  service_code TEXT NOT NULL,
  service_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'strategic'
    CHECK (category IN ('foundation', 'growth', 'strategic', 'operational')),

  -- The Blueprint (comprehensive JSON)
  blueprint JSONB NOT NULL DEFAULT '{}',

  -- Advisor edits tracking
  advisor_notes TEXT,
  edited_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  edited_at TIMESTAMPTZ,
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  implemented_at TIMESTAMPTZ,

  -- Generation metadata
  llm_model TEXT,
  generation_tokens INTEGER,
  generation_cost_usd DECIMAL(8,4),
  generation_duration_ms INTEGER,

  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX idx_blueprints_practice ON service_line_blueprints(practice_id);
CREATE INDEX idx_blueprints_status ON service_line_blueprints(status);
CREATE INDEX idx_blueprints_code ON service_line_blueprints(service_code);
CREATE INDEX idx_blueprints_source_concept ON service_line_blueprints(source_concept_id) WHERE source_concept_id IS NOT NULL;
CREATE INDEX idx_blueprints_source_opportunity ON service_line_blueprints(source_opportunity_id) WHERE source_opportunity_id IS NOT NULL;

-- RLS
ALTER TABLE service_line_blueprints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Practice members can view blueprints"
  ON service_line_blueprints FOR SELECT
  USING (
    practice_id IN (
      SELECT practice_id FROM practice_members
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Practice admins can insert blueprints"
  ON service_line_blueprints FOR INSERT
  WITH CHECK (
    practice_id IN (
      SELECT practice_id FROM practice_members
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'consultant')
    )
  );

CREATE POLICY "Practice admins can update blueprints"
  ON service_line_blueprints FOR UPDATE
  USING (
    practice_id IN (
      SELECT practice_id FROM practice_members
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'consultant')
    )
  );

CREATE POLICY "Service role full access blueprints"
  ON service_line_blueprints FOR ALL
  USING (auth.role() = 'service_role');

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_service_line_blueprints_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_blueprints_updated_at
  BEFORE UPDATE ON service_line_blueprints
  FOR EACH ROW EXECUTE FUNCTION update_service_line_blueprints_updated_at();

COMMENT ON TABLE service_line_blueprints IS 'Generated service line definitions from Service Line Builder; draft → reviewed → approved → implemented';
