-- ============================================================================
-- UPDATE MANAGEMENT ACCOUNTS ASSESSMENT QUESTIONS
-- ============================================================================
-- Migration: 20260115_update_ma_assessment_questions.sql
-- Purpose: Update assessment_questions table with the new 31-question
--          Management Accounts assessment structure
-- ============================================================================

-- Disable audit trigger to avoid practice_id error
ALTER TABLE assessment_questions DISABLE TRIGGER audit_assessment_questions;

-- Delete existing management_accounts questions
DELETE FROM assessment_questions WHERE service_line_code = 'management_accounts';

-- Insert updated Management Accounts assessment questions (31 questions across 8 sections)
-- Section 1: Current State (4 questions)
INSERT INTO assessment_questions (service_line_code, question_id, section, question_text, question_type, options, placeholder, char_limit, max_selections, emotional_anchor, technical_field, is_required, display_order, is_active) VALUES
('management_accounts', 'ma_relationship_with_numbers', 'Current State', 'How would you describe your current relationship with your business numbers?', 'single', '["I check them religiously every week", "I look at bank balance, that''s about it", "I wait for my accountant to tell me how we did", "Numbers stress me out - I avoid them", "I want to engage more but don''t know what to look at"]'::jsonb, NULL, NULL, NULL, 'relationship_with_numbers', NULL, true, 1, true),
('management_accounts', 'ma_reports_insight_frequency', 'Current State', 'When was the last time your financial reports told you something you didn''t already know?', 'single', '["Last week - they''re genuinely useful", "Last month - occasionally insightful", "Last quarter - rare \"aha\" moments", "Can''t remember - they just confirm what I suspected", "Never - I don''t understand them anyway"]'::jsonb, NULL, NULL, NULL, 'reports_insight_frequency', NULL, true, 2, true),
('management_accounts', 'ma_tuesday_financial_question', 'Current State', 'What''s your "Tuesday morning" financial question? The thing you wish you could instantly answer when you sit down?', 'text', NULL, 'E.g., "How much cash will we have in 30 days?" / "Which client is most profitable?"', 200, NULL, 'tuesday_financial_question', NULL, true, 3, true),
('management_accounts', 'ma_magic_away_financial', 'Current State', 'If you could magic away ONE financial uncertainty, what would it be?', 'text', NULL, 'Describe the financial worry that keeps you up at night...', 300, NULL, NULL, 'magic_away_financial', NULL, true, 4, true),

-- Section 2: Pain Points (3 questions)
('management_accounts', 'ma_pain_points', 'Pain Points', 'Which of these keep you awake at night? (Select all that apply)', 'multi', '["Not knowing if we''re actually profitable month-to-month", "Cash flow surprises - bills I forgot were coming", "Can''t tell which services/products make money", "Year-end tax bills are always a shock", "Don''t know if we can afford to hire", "No idea what our breakeven point is", "Bank balance looks healthy but profits feel thin", "Staff costs feel high but can''t prove it"]'::jsonb, NULL, NULL, NULL, 'kpi_priorities', NULL, true, 5, true),
('management_accounts', 'ma_reporting_lag', 'Pain Points', 'How long does it take you to answer "How did we do last month?"', 'single', '["Under a minute - I have it at my fingertips", "About 30 minutes - need to pull some reports", "A few hours - involves spreadsheets and reconciliations", "A few days - need to wait for bookkeeper", "No idea until year-end accounts"]'::jsonb, NULL, NULL, NULL, NULL, 'current_reporting_lag', true, 6, true),
('management_accounts', 'ma_decision_making_story', 'Pain Points', 'Last time you had a big business decision to make, how did financials inform it?', 'text', NULL, 'E.g., hiring, pricing, investment, taking on a big client...', 300, NULL, NULL, 'decision_making_story', NULL, true, 7, true),

-- Section 3: System Context (5 questions)
('management_accounts', 'ma_accounting_platform', 'System Context', 'What accounting software are you using?', 'single', '["Xero", "QuickBooks Online", "Sage (any version)", "FreeAgent", "Kashflow", "Spreadsheets", "Other"]'::jsonb, NULL, NULL, NULL, NULL, 'accounting_platform', true, 8, true),
('management_accounts', 'ma_bookkeeping_currency', 'System Context', 'How up-to-date is your bookkeeping typically?', 'single', '["Real-time - everything''s entered within days", "Weekly - usually caught up by Friday", "Monthly - we batch it up", "Quarterly - we do it for VAT", "Whenever someone has time"]'::jsonb, NULL, NULL, NULL, NULL, 'bookkeeping_currency', true, 9, true),
('management_accounts', 'ma_bookkeeping_owner', 'System Context', 'Who currently does your bookkeeping?', 'single', '["I do it myself", "An internal team member", "An external bookkeeper/accountant", "A mix - different people for different things", "Nobody consistently"]'::jsonb, NULL, NULL, NULL, NULL, 'bookkeeping_owner', true, 10, true),
('management_accounts', 'ma_chart_of_accounts_granularity', 'System Context', 'How granular is your chart of accounts?', 'single', '["Very detailed - we track by service line, department, and project", "Moderately detailed - main categories plus some breakdown", "Basic - standard P&L categories only", "I don''t know"]'::jsonb, NULL, NULL, NULL, NULL, 'chart_of_accounts_granularity', true, 11, true),
('management_accounts', 'ma_revenue_tracking', 'System Context', 'Do you track revenue by customer or service line in your accounting system?', 'single', '["Yes, both customer and service line", "Yes, by customer only", "Yes, by service line only", "No, but we could set it up", "No, and it would be difficult"]'::jsonb, NULL, NULL, NULL, NULL, 'revenue_tracking', true, 12, true),

-- Section 4: Business Model (6 questions)
('management_accounts', 'ma_revenue_model', 'Business Model', 'How would you describe your revenue model?', 'single', '["Mostly recurring (retainers, subscriptions, maintenance contracts)", "Mostly project-based (fixed fee or time-based projects)", "Mostly product sales (physical or digital products)", "Mixed - roughly equal split", "Transactional (one-off sales, no ongoing relationship)"]'::jsonb, NULL, NULL, NULL, NULL, 'revenue_model', true, 13, true),
('management_accounts', 'ma_payment_terms_given', 'Business Model', 'What payment terms do you typically give customers?', 'single', '["Payment upfront or on delivery", "7-14 days", "30 days", "30-60 days", "60+ days", "It varies widely"]'::jsonb, NULL, NULL, NULL, NULL, 'payment_terms_given', true, 14, true),
('management_accounts', 'ma_seasonality', 'Business Model', 'How seasonal is your business?', 'single', '["Very seasonal - revenue can vary 50%+ between peak and trough months", "Somewhat seasonal - noticeable peaks but manageable", "Fairly stable - minor fluctuations month to month", "Counter-cyclical - busy when others are quiet"]'::jsonb, NULL, NULL, NULL, NULL, 'seasonality', true, 15, true),
('management_accounts', 'ma_customer_concentration', 'Business Model', 'If your top 3 customers left tomorrow, what % of revenue would you lose?', 'single', '["Over 50% - we''re heavily concentrated", "30-50% - concentrated but not critical", "15-30% - reasonably diversified", "Under 15% - very diversified", "I don''t actually know"]'::jsonb, NULL, NULL, NULL, NULL, 'customer_concentration', true, 16, true),
('management_accounts', 'ma_employee_count', 'Business Model', 'How many employees (or FTE equivalent) do you have?', 'single', '["Just me", "2-5", "6-10", "11-25", "26-50", "50+"]'::jsonb, NULL, NULL, NULL, NULL, 'employee_count', true, 17, true),
('management_accounts', 'ma_annual_revenue', 'Business Model', 'What''s your approximate annual revenue?', 'single', '["Under £250k", "£250k - £500k", "£500k - £1m", "£1m - £2m", "£2m - £5m", "£5m+"]'::jsonb, NULL, NULL, NULL, NULL, 'annual_revenue', true, 18, true),

-- Section 5: Known Commitments (4 questions)
('management_accounts', 'ma_upcoming_expenses', 'Known Commitments', 'What significant expenses do you have coming up in the next 90 days?', 'multi', '["VAT payment", "Corporation tax payment", "Large supplier invoice", "Equipment or vehicle purchase", "Bonus or commission payments", "Loan repayment", "Dividend payment", "Nothing significant planned", "Other"]'::jsonb, NULL, NULL, NULL, NULL, 'upcoming_expenses', true, 19, true),
('management_accounts', 'ma_planned_hires', 'Known Commitments', 'Are you planning to hire anyone in the next 6 months?', 'single', '["Yes, definitely", "Possibly, depends on circumstances", "No plans to hire", "Actually planning to reduce headcount"]'::jsonb, NULL, NULL, NULL, NULL, 'planned_hires', true, 20, true),
('management_accounts', 'ma_debt_lease_payments', 'Known Commitments', 'Do you have any debt or lease payments?', 'single', '["Yes - loans with regular repayments", "Yes - asset finance / HP agreements", "Yes - both loans and asset finance", "No debt or lease commitments"]'::jsonb, NULL, NULL, NULL, NULL, 'debt_lease_payments', true, 21, true),
('management_accounts', 'ma_year_end_month', 'Known Commitments', 'When is your financial year end?', 'single', '["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]'::jsonb, NULL, NULL, NULL, NULL, 'year_end_month', true, 22, true),

-- Section 6: Reporting Requirements (4 questions)
('management_accounts', 'ma_report_recipients', 'Reporting Requirements', 'Who needs to see your management accounts?', 'multi', '["Just me", "My business partner(s)", "Leadership team / department heads", "Board of directors", "Bank or lender", "Investors", "Other"]'::jsonb, NULL, NULL, NULL, NULL, 'report_recipients', true, 23, true),
('management_accounts', 'ma_budget_forecast', 'Reporting Requirements', 'Do you have a budget or forecast to compare against?', 'single', '["Yes, detailed budget by month", "Yes, but high-level / annual only", "No, but I''d like one", "No, and not a priority right now"]'::jsonb, NULL, NULL, NULL, NULL, 'budget_forecast', true, 24, true),
('management_accounts', 'ma_report_format', 'Reporting Requirements', 'How do you want to receive your management accounts?', 'multi', '["PDF report I can read on my phone", "Interactive dashboard I can explore", "Board pack with commentary", "Excel file I can manipulate", "All of the above"]'::jsonb, NULL, NULL, NULL, NULL, 'report_format', true, 25, true),
('management_accounts', 'ma_prior_year_comparison', 'Reporting Requirements', 'Do you need to compare to prior year?', 'single', '["Yes, and we have good prior year data", "Yes, but our prior year data is messy", "No, we''re too new / prior year isn''t relevant", "No, we don''t need that"]'::jsonb, NULL, NULL, NULL, NULL, 'prior_year_comparison', true, 26, true),

-- Section 7: Desired Outcomes (2 questions)
('management_accounts', 'ma_transformation_desires', 'Desired Outcomes', 'If we delivered management accounts that actually worked for you, what would change?', 'multi', '["I''d make faster decisions", "I''d sleep better at night", "I''d have confident conversations with investors/banks", "I''d know when to push growth vs pull back", "I''d stop second-guessing my pricing", "I''d catch problems before they became crises", "I''d finally feel \"in control\" of the finances", "My spouse would stop worrying"]'::jsonb, NULL, NULL, 3, 'ma_transformation_desires', NULL, true, 27, true),
('management_accounts', 'ma_visibility_vision', 'Desired Outcomes', 'What does "financial visibility" look like to you? Paint the picture.', 'text', NULL, 'Describe your ideal state - how it feels, what you can do, what questions you can answer...', 400, NULL, NULL, 'financial_visibility_vision', NULL, true, 28, true),

-- Section 8: Frequency & Scope (3 questions)
('management_accounts', 'ma_reporting_frequency', 'Frequency & Scope', 'How often do you realistically need to see your numbers to make good decisions?', 'single', '["Weekly - we move fast", "Monthly - that''s the right rhythm", "Quarterly - we''re stable enough", "I don''t know what''s appropriate for us"]'::jsonb, NULL, NULL, NULL, NULL, 'reporting_frequency_preference', true, 29, true),
('management_accounts', 'ma_additional_analysis', 'Frequency & Scope', 'What specific additional analysis would be valuable?', 'multi', '["Cash flow forecasting (30/60/90 day projections)", "\"What if\" scenario modeling (e.g., impact of hiring, price changes)", "Rolling trend analysis (6-12 month patterns)", "Debtor analysis (who owes what, how old)", "Profitability by service line or customer", "Staff cost and productivity analysis", "Working capital optimization", "None of these - just the basics please"]'::jsonb, NULL, NULL, NULL, NULL, 'additional_analysis_needs', true, 30, true),
('management_accounts', 'ma_upcoming_decisions', 'Frequency & Scope', 'What decisions do you have coming up that better numbers would help with?', 'multi', '["Hiring decisions", "Pricing decisions", "Investment / capex decisions", "Acquisition opportunities", "Exit or sale preparation", "Funding / borrowing decisions", "Premises decisions", "None specific right now"]'::jsonb, NULL, NULL, NULL, NULL, 'upcoming_decisions', true, 31, true);

-- Re-enable audit trigger
ALTER TABLE assessment_questions ENABLE TRIGGER audit_assessment_questions;
