/**
 * Discovery Opportunity Panel
 * 
 * Displays all identified opportunities for a discovery engagement,
 * loaded from discovery_opportunities table (generated by Pass 3).
 * 
 * Features:
 * - View all opportunities with details
 * - Service recommendations with pricing
 * - New service concepts flagged for review
 * - Mark opportunities to show in client view
 * - Create new service lines from opportunities/concepts
 */

import { useState, useEffect } from 'react';
import { 
  ChevronDown,
  Copy,
  Check,
  Sparkles,
  Plus,
  Loader2,
  Eye,
  EyeOff,
  RefreshCw
} from 'lucide-react';
import { supabase } from '../../lib/supabase';

// ============================================================================
// Types
// ============================================================================

interface Service {
  id: string;
  code: string;
  name: string;
  price_amount?: number;
  price_period?: string;
}

interface Concept {
  id: string;
  suggested_name: string;
  problem_it_solves: string;
  suggested_pricing?: string;
  times_identified: number;
  review_status: string;
}

interface Opportunity {
  id: string;
  opportunity_code: string;
  title: string;
  description: string;
  category: string;
  severity: 'critical' | 'high' | 'medium' | 'low' | 'opportunity';
  financial_impact_amount?: number;
  financial_impact_type?: string;
  life_impact?: string;
  recommended_service_id?: string;
  service_fit_score?: number;
  service_fit_rationale?: string;
  service_fit_limitation?: string;
  suggested_concept_id?: string;
  talking_point?: string;
  question_to_ask?: string;
  quick_win?: string;
  show_in_client_view?: boolean;
  service?: Service;
  concept?: Concept;
  generated_at?: string;
  // Rich fields (match benchmarking)
  priority?: 'must_address_now' | 'next_3_months' | 'next_12_months' | 'when_ready';
  data_evidence?: string;
  data_values?: { benchmarkComparison?: string; priorityRationale?: string; [k: string]: unknown };
  impact_calculation?: string;
  financial_impact_confidence?: string;
}

interface Props {
  engagementId: string;
  clientId?: string;
  practiceId?: string;
  onVisibilityChange?: () => void;  // Callback when visibility changes
}

// ============================================================================
// Component
// ============================================================================

export function DiscoveryOpportunityPanel({ engagementId, clientId: _clientId, practiceId, onVisibilityChange }: Props) {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [updating, setUpdating] = useState<string | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [createServiceData, setCreateServiceData] = useState<any>(null);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    if (engagementId) {
      loadOpportunities();
    }
  }, [engagementId]);

  const loadOpportunities = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const { data, error: fetchError } = await supabase
        .from('discovery_opportunities')
        .select(`
          *,
          service:services(id, code, name, price_amount, price_period),
          concept:service_concepts(id, suggested_name, problem_it_solves, suggested_pricing, times_identified, review_status)
        `)
        .eq('engagement_id', engagementId)
        .order('generated_at', { ascending: false });
      
      if (fetchError) throw fetchError;
      
      setOpportunities(data || []);
    } catch (err) {
      console.error('Failed to load opportunities:', err);
      setError('Failed to load opportunities');
    }
    
    setLoading(false);
  };

  const handleToggleClientView = async (opportunityId: string, currentValue: boolean) => {
    setUpdating(opportunityId);
    try {
      const { error: updateError } = await supabase
        .from('discovery_opportunities')
        .update({ show_in_client_view: !currentValue })
        .eq('id', opportunityId);
      
      if (updateError) throw updateError;
      
      // Update local state
      setOpportunities(prev => prev.map(opp => 
        opp.id === opportunityId 
          ? { ...opp, show_in_client_view: !currentValue }
          : opp
      ));
    } catch (err) {
      console.error('Failed to update opportunity:', err);
      alert('Failed to update opportunity visibility');
    } finally {
      setUpdating(null);
    }
  };

  const handleCopyTalkingPoint = async (text: string, opportunityId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(opportunityId);
      setTimeout(() => setCopiedId(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const parsePriceFromConcept = (suggestedPricing: string | undefined): string => {
    if (!suggestedPricing) return '';
    const match = suggestedPricing.match(/£\s*([\d,]+)/);
    return match ? match[1].replace(/,/g, '') : '';
  };

  const handleCreateService = async (opportunityId: string, conceptId?: string) => {
    // Find the opportunity
    const opp = opportunities.find(o => o.id === opportunityId);
    if (!opp) return;
    
    if (conceptId && opp.concept) {
      // New concept → pre-fill modal (parse suggested_pricing e.g. "£3,000-£5,000 project")
      setCreateServiceData({
        opportunityId,
        conceptId,
        name: opp.concept.suggested_name,
        category: opp.category || 'strategic',
        description: opp.concept.problem_it_solves,
        suggestedPricing: parsePriceFromConcept(opp.concept.suggested_pricing),
        pricingModel: 'fixed',
      });
      setShowCreateModal(true);
    } else if (opp.service) {
      // Existing service → just toggle visibility
      await handleToggleClientView(opportunityId, true);
    }
  };

  const formatPriceDisplay = (amount: number, model: string): string => {
    if (!amount) return 'Price on request';
    const formatted = `£${amount.toLocaleString()}`;
    switch (model) {
      case 'monthly': return `${formatted}/mo`;
      case 'annual': return `${formatted}/year`;
      case 'fixed':
      default: return `${formatted} one-off`;
    }
  };

  const handleConfirmCreateService = async () => {
    if (!createServiceData || !practiceId) {
      alert('Practice ID is required to create services');
      return;
    }
    setCreating(true);
    
    try {
      const code = createServiceData.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '');
      const priceAmount = Number.parseFloat(createServiceData.suggestedPricing) || null;
      const pricingModel = createServiceData.pricingModel || 'fixed';
      const priceDisplay = priceAmount != null ? formatPriceDisplay(priceAmount, pricingModel) : null;
      
      const { data: newService, error: serviceError } = await supabase
        .from('services')
        .insert({
          code,
          name: createServiceData.name,
          short_description: createServiceData.description,
          category: createServiceData.category,
          price_amount: priceAmount,
          price_period: pricingModel === 'monthly' ? 'month' : pricingModel === 'annual' ? 'year' : 'one-off',
          price_display: priceDisplay,
          status: 'active',
          practice_id: practiceId,
          created_at: new Date().toISOString(),
        })
        .select()
        .single();
      
      if (serviceError) throw serviceError;
      
      console.log('[DiscoveryOpportunityPanel] Created new service:', newService);
      
      // 2. Update the concept status
      if (createServiceData.conceptId) {
        await supabase
          .from('service_concepts')
          .update({
            review_status: 'approved',
            created_service_id: newService.id,
            updated_at: new Date().toISOString()
          })
          .eq('id', createServiceData.conceptId);
      }
      
      // 3. Link the opportunity to the new service
      await supabase
        .from('discovery_opportunities')
        .update({
          recommended_service_id: newService.id,
          suggested_concept_id: null,
          show_in_client_view: true
        })
        .eq('id', createServiceData.opportunityId);
      
      // 4. Refresh
      setShowCreateModal(false);
      setCreateServiceData(null);
      await loadOpportunities();
      if (onVisibilityChange) onVisibilityChange();
      
    } catch (err) {
      console.error('Failed to create service:', err);
      alert(`Failed to create service: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setCreating(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-6 h-6 animate-spin text-indigo-600" />
        <span className="ml-2 text-gray-600">Loading opportunities...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
        <p className="text-red-800">{error}</p>
      </div>
    );
  }

  if (opportunities.length === 0) {
    return (
      <div className="text-center py-12">
        <Sparkles className="w-12 h-12 mx-auto mb-3 text-gray-400" />
        <p className="text-gray-600">No opportunities identified yet</p>
        <p className="text-sm text-gray-500 mt-1">Run Pass 3 to generate opportunities</p>
      </div>
    );
  }

  const priorityGroups = [
    { key: 'must_address_now' as const, label: '🚨 Must Address Now', subtitle: 'These block your stated goal', bgClass: 'bg-red-50 border-red-200', textClass: 'text-red-900' },
    { key: 'next_3_months' as const, label: '⚠️ Address Within 3 Months', subtitle: 'Important but not blocking', bgClass: 'bg-amber-50 border-amber-200', textClass: 'text-amber-900' },
    { key: 'next_12_months' as const, label: '📋 Next 12 Months', subtitle: 'Important but not blocking', bgClass: 'bg-blue-50 border-blue-200', textClass: 'text-blue-900' },
    { key: 'when_ready' as const, label: '💡 When Ready', subtitle: 'Optimisation opportunities', bgClass: 'bg-gray-50 border-gray-200', textClass: 'text-gray-900' },
  ];

  const groupedByPriority = priorityGroups
    .map(group => ({
      ...group,
      opportunities: opportunities.filter(o => (o.priority || 'when_ready') === group.key),
    }))
    .filter(group => group.opportunities.length > 0);

  const totalValue = opportunities.reduce((s, o) => s + (o.financial_impact_amount || 0), 0);

  return (
    <div className="space-y-8">
      {/* Summary bar */}
      <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-semibold text-indigo-900">Opportunities Identified</h3>
            <p className="text-sm text-indigo-700 mt-1">
              {opportunities.length} total • {opportunities.filter(o => o.show_in_client_view).length} shown to client
              • £{totalValue.toLocaleString()} total value
            </p>
          </div>
          <button onClick={loadOpportunities} className="px-3 py-1.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm flex items-center gap-2">
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        </div>
      </div>

      {/* Priority Groups */}
      {groupedByPriority.map(group => (
        <div key={group.key} className="space-y-3">
          <div className={`p-3 rounded-lg border ${group.bgClass}`}>
            <h4 className={`font-semibold ${group.textClass}`}>{group.label}</h4>
            <p className={`text-xs ${group.textClass} opacity-70`}>{group.subtitle}</p>
          </div>
          <div className="space-y-3 pl-2">
            {group.opportunities.map((opp) => {
              const isExpanded = expandedId === opp.id;
              return (
                <div key={opp.id} className="border rounded-lg overflow-hidden hover:shadow-md transition-shadow bg-white">
                  {/* Collapsed Header */}
                  <div
                    role="button"
                    tabIndex={0}
                    className="p-4 cursor-pointer flex items-start justify-between"
                    onClick={() => setExpandedId(isExpanded ? null : opp.id)}
                    onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setExpandedId(isExpanded ? null : opp.id); } }}
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1.5">
                        <span className={`px-2 py-0.5 text-xs font-bold rounded ${
                          opp.severity === 'critical' ? 'bg-red-100 text-red-700' :
                          opp.severity === 'high' ? 'bg-orange-100 text-orange-700' :
                          opp.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                          'bg-gray-100 text-gray-600'
                        }`}>
                          {(opp.severity || 'medium').toUpperCase()}
                        </span>
                        <span className="px-2 py-0.5 text-xs bg-slate-100 text-slate-600 rounded flex items-center gap-1">
                          📁 {opp.category || 'General'}
                        </span>
                        {opp.data_values?.priorityRationale && (
                          <span className="px-2 py-0.5 text-xs bg-purple-100 text-purple-700 rounded">
                            ⚡ Priority adjusted
                          </span>
                        )}
                      </div>
                      <h4 className="font-semibold text-gray-900">{opp.title}</h4>
                    </div>
                    <div className="flex items-center gap-3 ml-4">
                      {opp.financial_impact_amount != null && (
                        <span className="text-lg font-semibold text-emerald-700">
                          £{opp.financial_impact_amount >= 1000000
                            ? `${(opp.financial_impact_amount / 1000000).toFixed(1)}M`
                            : opp.financial_impact_amount >= 1000
                            ? `${(opp.financial_impact_amount / 1000).toFixed(0)}k`
                            : opp.financial_impact_amount.toLocaleString()}
                        </span>
                      )}
                      <button
                        onClick={(e) => { e.stopPropagation(); handleToggleClientView(opp.id, opp.show_in_client_view || false); }}
                        disabled={updating === opp.id}
                        className={`p-1.5 rounded-lg transition-colors ${
                          opp.show_in_client_view
                            ? 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200'
                            : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                        }`}
                        title={opp.show_in_client_view ? 'Visible to client' : 'Hidden from client'}
                      >
                        {updating === opp.id ? <Loader2 className="w-4 h-4 animate-spin" /> : opp.show_in_client_view ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
                      </button>
                      <ChevronDown className={`w-5 h-5 text-gray-400 transition-transform flex-shrink-0 ${isExpanded ? 'rotate-180' : ''}`} />
                    </div>
                  </div>

                  {/* Expanded Body */}
                  {isExpanded && (
                    <div className="border-t px-4 pb-4 space-y-4 bg-gray-50/50">
                      {opp.data_evidence && (
                        <div className="pt-4">
                          <p className="text-sm text-gray-800 leading-relaxed">{opp.data_evidence}</p>
                        </div>
                      )}
                      {opp.data_values?.benchmarkComparison && (
                        <p className="text-sm text-gray-600 italic">{opp.data_values.benchmarkComparison}</p>
                      )}
                      {opp.impact_calculation && (
                        <p className="text-xs text-gray-500 leading-relaxed">Impact calculation: {opp.impact_calculation}</p>
                      )}
                      {opp.life_impact && (
                        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                          <p className="text-sm">
                            <span className="font-bold text-red-700">FOR THE OWNER: </span>
                            <span className="text-red-800">{opp.life_impact}</span>
                          </p>
                        </div>
                      )}
                      {opp.talking_point && (
                        <div className="bg-white border border-gray-200 rounded-lg p-4">
                          <div className="flex items-start justify-between gap-3">
                            <div className="flex-1">
                              <p className="text-xs font-bold text-gray-500 mb-2 flex items-center gap-1.5">💬 SAY THIS:</p>
                              <p className="text-sm text-gray-800 italic leading-relaxed">&quot;{opp.talking_point}&quot;</p>
                            </div>
                            <button
                              onClick={(e) => { e.stopPropagation(); handleCopyTalkingPoint(opp.talking_point!, opp.id); }}
                              className="p-2 rounded-lg hover:bg-gray-100 transition-colors flex-shrink-0"
                              title="Copy to clipboard"
                            >
                              {copiedId === opp.id ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-gray-400" />}
                            </button>
                          </div>
                        </div>
                      )}
                      {opp.question_to_ask && (
                        <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-4">
                          <p className="text-sm">
                            <span className="font-bold text-indigo-700">ASK: </span>
                            <span className="text-indigo-800">&quot;{opp.question_to_ask}&quot;</span>
                          </p>
                        </div>
                      )}
                      {opp.quick_win && (
                        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                          <p className="text-sm">
                            <span className="font-bold text-amber-700">⚡ QUICK WIN: </span>
                            <span className="text-amber-800">{opp.quick_win}</span>
                          </p>
                        </div>
                      )}
                      {opp.concept && (
                        <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                          <div className="flex items-start justify-between">
                            <div>
                              <div className="flex items-center gap-2 mb-2">
                                <span className="text-xs font-bold text-purple-700 flex items-center gap-1">✨ NEW SERVICE CONCEPT</span>
                                {opp.concept.times_identified != null && opp.concept.times_identified > 1 && (
                                  <span className="px-2 py-0.5 text-xs bg-purple-200 text-purple-700 rounded-full">
                                    Seen {opp.concept.times_identified}× across clients
                                  </span>
                                )}
                              </div>
                              <h5 className="font-semibold text-purple-900">{opp.concept.suggested_name}</h5>
                              <p className="text-sm text-purple-700 mt-1">{opp.concept.problem_it_solves}</p>
                            </div>
                            <button
                              onClick={(e) => { e.stopPropagation(); handleCreateService(opp.id, opp.concept?.id); }}
                              className="px-3 py-1.5 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm flex items-center gap-1 flex-shrink-0"
                            >
                              <Plus className="w-4 h-4" />
                              Create Service
                            </button>
                          </div>
                        </div>
                      )}
                      {opp.service && !opp.concept && (
                        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                          <div className="flex items-start justify-between">
                            <div>
                              <p className="text-xs font-bold text-blue-600 mb-1">RECOMMENDED SERVICE</p>
                              <h5 className="font-semibold text-blue-900">{opp.service.name}</h5>
                              {opp.service.price_amount != null && (
                                <p className="text-sm text-blue-700 mt-1">
                                  £{opp.service.price_amount.toLocaleString()}
                                  {opp.service.price_period === 'month' ? '/mo' : ''}
                                </p>
                              )}
                              {opp.service_fit_rationale && <p className="text-xs text-blue-600 mt-2">{opp.service_fit_rationale}</p>}
                              {opp.service_fit_limitation && <p className="text-xs text-blue-500 mt-1 italic">Limitation: {opp.service_fit_limitation}</p>}
                            </div>
                            {opp.service_fit_score != null && (
                              <span className="px-2 py-1 bg-blue-200 text-blue-800 text-xs font-bold rounded">{opp.service_fit_score}% fit</span>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ))}

      {/* Create Service Modal */}
      {showCreateModal && createServiceData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-6">
            <h3 className="text-lg font-semibold mb-4">Create New Service</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Service Name</label>
                <input
                  type="text"
                  value={createServiceData.name}
                  onChange={(e) => setCreateServiceData({ ...createServiceData, name: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  value={createServiceData.description}
                  onChange={(e) => setCreateServiceData({ ...createServiceData, description: e.target.value })}
                  rows={3}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Price (£)</label>
                  <input
                    type="number"
                    value={createServiceData.suggestedPricing}
                    onChange={(e) => setCreateServiceData({ ...createServiceData, suggestedPricing: e.target.value })}
                    className="w-full px-3 py-2 border rounded-lg"
                    placeholder="e.g. 2000"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Pricing Model</label>
                  <select
                    value={createServiceData.pricingModel}
                    onChange={(e) => setCreateServiceData({ ...createServiceData, pricingModel: e.target.value })}
                    className="w-full px-3 py-2 border rounded-lg"
                  >
                    <option value="fixed">One-off</option>
                    <option value="month">Monthly</option>
                    <option value="annual">Annual</option>
                  </select>
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                <select
                  value={createServiceData.category}
                  onChange={(e) => setCreateServiceData({ ...createServiceData, category: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                >
                  <option value="financial">Financial</option>
                  <option value="operational">Operational</option>
                  <option value="strategic">Strategic</option>
                  <option value="personal">Personal</option>
                  <option value="wealth">Wealth</option>
                </select>
              </div>
            </div>
            
            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => { setShowCreateModal(false); setCreateServiceData(null); }}
                className="px-4 py-2 text-gray-700 border rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmCreateService}
                disabled={creating || !createServiceData.name}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 flex items-center gap-2"
              >
                {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
                Create Service
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
