/**
 * Discovery Opportunity Panel
 * 
 * Displays all identified opportunities for a discovery engagement,
 * loaded from discovery_opportunities table (generated by Pass 3).
 * 
 * Features:
 * - View all opportunities with details
 * - Service recommendations with pricing
 * - New service concepts flagged for review
 * - Mark opportunities to show in client view
 * - Create new service lines from opportunities/concepts
 */

import { useState, useEffect } from 'react';
import { 
  Lightbulb, 
  ChevronDown,
  ChevronRight,
  Copy,
  Check,
  Sparkles,
  Target,
  DollarSign,
  Plus,
  Loader2,
  Eye,
  EyeOff,
  Settings,
  RefreshCw
} from 'lucide-react';
import { supabase } from '../../lib/supabase';

// ============================================================================
// Types
// ============================================================================

interface Service {
  id: string;
  code: string;
  name: string;
  price_amount?: number;
  price_period?: string;
}

interface Concept {
  id: string;
  suggested_name: string;
  problem_it_solves: string;
  times_identified: number;
  review_status: string;
}

interface Opportunity {
  id: string;
  opportunity_code: string;
  title: string;
  description: string;
  category: string;
  severity: 'critical' | 'high' | 'medium' | 'low' | 'opportunity';
  financial_impact_amount?: number;
  financial_impact_type?: string;
  life_impact?: string;
  recommended_service_id?: string;
  service_fit_score?: number;
  service_fit_rationale?: string;
  suggested_concept_id?: string;
  talking_point?: string;
  question_to_ask?: string;
  quick_win?: string;
  show_in_client_view?: boolean;
  service?: Service;
  concept?: Concept;
  generated_at?: string;
}

interface Props {
  engagementId: string;
  clientId?: string;
  practiceId?: string;
  onVisibilityChange?: () => void;  // Callback when visibility changes
}

// ============================================================================
// Component
// ============================================================================

export function DiscoveryOpportunityPanel({ engagementId, clientId, practiceId, onVisibilityChange }: Props) {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [updating, setUpdating] = useState<string | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [createServiceData, setCreateServiceData] = useState<any>(null);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    if (engagementId) {
      loadOpportunities();
    }
  }, [engagementId]);

  const loadOpportunities = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const { data, error: fetchError } = await supabase
        .from('discovery_opportunities')
        .select(`
          *,
          service:services(id, code, name, price_amount, price_period),
          concept:service_concepts(id, suggested_name, problem_it_solves, times_identified, review_status)
        `)
        .eq('engagement_id', engagementId)
        .order('generated_at', { ascending: false });
      
      if (fetchError) throw fetchError;
      
      setOpportunities(data || []);
    } catch (err) {
      console.error('Failed to load opportunities:', err);
      setError('Failed to load opportunities');
    }
    
    setLoading(false);
  };

  const handleToggleClientView = async (opportunityId: string, currentValue: boolean) => {
    setUpdating(opportunityId);
    try {
      const { error: updateError } = await supabase
        .from('discovery_opportunities')
        .update({ show_in_client_view: !currentValue })
        .eq('id', opportunityId);
      
      if (updateError) throw updateError;
      
      // Update local state
      setOpportunities(prev => prev.map(opp => 
        opp.id === opportunityId 
          ? { ...opp, show_in_client_view: !currentValue }
          : opp
      ));
    } catch (err) {
      console.error('Failed to update opportunity:', err);
      alert('Failed to update opportunity visibility');
    } finally {
      setUpdating(null);
    }
  };

  const handleCopyTalkingPoint = async (text: string, opportunityId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(opportunityId);
      setTimeout(() => setCopiedId(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleCreateService = async (opportunityId: string, conceptId?: string) => {
    // Find the opportunity
    const opp = opportunities.find(o => o.id === opportunityId);
    if (!opp) return;
    
    if (conceptId && opp.concept) {
      // New concept → pre-fill modal
      setCreateServiceData({
        opportunityId,
        conceptId,
        name: opp.concept.suggested_name,
        category: opp.category,
        description: opp.concept.problem_it_solves,
        suggestedPricing: '',
        pricingModel: 'fixed',
      });
      setShowCreateModal(true);
    } else if (opp.service) {
      // Existing service → just toggle visibility
      await handleToggleClientView(opportunityId, true);
    }
  };

  const handleConfirmCreateService = async () => {
    if (!createServiceData || !practiceId) {
      alert('Practice ID is required to create services');
      return;
    }
    setCreating(true);
    
    try {
      // 1. Create the service
      const code = createServiceData.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '');
      
      const { data: newService, error: serviceError } = await supabase
        .from('services')
        .insert({
          code,
          name: createServiceData.name,
          short_description: createServiceData.description,
          category: createServiceData.category,
          price_amount: parseFloat(createServiceData.suggestedPricing) || null,
          price_period: createServiceData.pricingModel,
          status: 'active',
          practice_id: practiceId,
          created_at: new Date().toISOString(),
        })
        .select()
        .single();
      
      if (serviceError) throw serviceError;
      
      console.log('[DiscoveryOpportunityPanel] Created new service:', newService);
      
      // 2. Update the concept status
      if (createServiceData.conceptId) {
        await supabase
          .from('service_concepts')
          .update({
            review_status: 'approved',
            promoted_to_service_id: newService.id,
            updated_at: new Date().toISOString()
          })
          .eq('id', createServiceData.conceptId);
      }
      
      // 3. Link the opportunity to the new service
      await supabase
        .from('discovery_opportunities')
        .update({
          recommended_service_id: newService.id,
          suggested_concept_id: null,
          show_in_client_view: true
        })
        .eq('id', createServiceData.opportunityId);
      
      // 4. Refresh
      setShowCreateModal(false);
      setCreateServiceData(null);
      await loadOpportunities();
      if (onVisibilityChange) onVisibilityChange();
      
    } catch (err) {
      console.error('Failed to create service:', err);
      alert(`Failed to create service: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setCreating(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-6 h-6 animate-spin text-indigo-600" />
        <span className="ml-2 text-gray-600">Loading opportunities...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
        <p className="text-red-800">{error}</p>
      </div>
    );
  }

  if (opportunities.length === 0) {
    return (
      <div className="text-center py-12">
        <Sparkles className="w-12 h-12 mx-auto mb-3 text-gray-400" />
        <p className="text-gray-600">No opportunities identified yet</p>
        <p className="text-sm text-gray-500 mt-1">Run Pass 3 to generate opportunities</p>
      </div>
    );
  }

  const groupedByCategory = opportunities.reduce((acc, opp) => {
    const cat = opp.category || 'Other';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(opp);
    return acc;
  }, {} as Record<string, Opportunity[]>);

  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-semibold text-indigo-900">Opportunities Identified</h3>
            <p className="text-sm text-indigo-700 mt-1">
              {opportunities.length} total • {opportunities.filter(o => o.show_in_client_view).length} shown to client
            </p>
          </div>
          <button
            onClick={loadOpportunities}
            className="px-3 py-1.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm flex items-center gap-2"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        </div>
      </div>

      {/* Opportunities by Category */}
      {Object.entries(groupedByCategory).map(([category, categoryOpps]) => (
        <div key={category} className="space-y-3">
          <h4 className="font-semibold text-gray-900 flex items-center gap-2">
            <Target className="w-4 h-4 text-indigo-600" />
            {category}
          </h4>
          
          {categoryOpps.map((opp) => {
            const isExpanded = expandedId === opp.id;
            const isCopied = copiedId === opp.id;
            const hasService = !!opp.service;
            const hasConcept = !!opp.concept;
            
            return (
              <div
                key={opp.id}
                className="bg-white border border-gray-200 rounded-lg overflow-hidden hover:border-indigo-300 transition-colors"
              >
                {/* Header */}
                <div className="p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h5 className="font-semibold text-gray-900">{opp.title}</h5>
                        {opp.show_in_client_view && (
                          <span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 text-xs rounded-full flex items-center gap-1">
                            <Eye className="w-3 h-3" />
                            Client View
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-gray-600 line-clamp-2">{opp.description}</p>
                    </div>
                    
                    <div className="flex items-center gap-2 ml-4">
                      {/* Toggle Client View */}
                      <button
                        onClick={() => handleToggleClientView(opp.id, opp.show_in_client_view || false)}
                        disabled={updating === opp.id}
                        className={`p-2 rounded-lg transition-colors ${
                          opp.show_in_client_view
                            ? 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200'
                            : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                        }`}
                        title={opp.show_in_client_view ? 'Hide from client' : 'Show to client'}
                      >
                        {updating === opp.id ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : opp.show_in_client_view ? (
                          <Eye className="w-4 h-4" />
                        ) : (
                          <EyeOff className="w-4 h-4" />
                        )}
                      </button>
                      
                      {/* Expand/Collapse */}
                      <button
                        onClick={() => setExpandedId(isExpanded ? null : opp.id)}
                        className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
                      >
                        {isExpanded ? (
                          <ChevronDown className="w-4 h-4 text-gray-600" />
                        ) : (
                          <ChevronRight className="w-4 h-4 text-gray-600" />
                        )}
                      </button>
                    </div>
                  </div>
                  
                  {/* Quick Info */}
                  <div className="flex items-center gap-4 mt-3 text-sm">
                    {opp.financial_impact_amount && (
                      <div className="flex items-center gap-1 text-emerald-700">
                        <DollarSign className="w-4 h-4" />
                        <span>£{opp.financial_impact_amount.toLocaleString()}</span>
                      </div>
                    )}
                    {hasService && (
                      <div className="flex items-center gap-1 text-blue-700">
                        <Target className="w-4 h-4" />
                        <span>{opp.service?.name}</span>
                      </div>
                    )}
                    {hasConcept && (
                      <div className="flex items-center gap-1 text-purple-700">
                        <Lightbulb className="w-4 h-4" />
                        <span>New Concept: {opp.concept?.suggested_name}</span>
                      </div>
                    )}
                  </div>
                </div>
                
                {/* Expanded Details */}
                {isExpanded && (
                  <div className="border-t border-gray-200 p-4 space-y-4 bg-gray-50">
                    {/* Service Recommendation */}
                    {hasService && (
                      <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                        <div className="flex items-start justify-between">
                          <div>
                            <h6 className="font-semibold text-blue-900 mb-1">Recommended Service</h6>
                            <p className="text-sm text-blue-800">{opp.service?.name}</p>
                            {opp.service?.price_amount && (
                              <p className="text-sm text-blue-700 mt-1">
                                £{opp.service.price_amount.toLocaleString()}{opp.service.price_period === 'month' ? '/mo' : opp.service.price_period === 'one-off' ? ' one-off' : ''}
                              </p>
                            )}
                            {opp.service_fit_rationale && (
                              <p className="text-xs text-blue-600 mt-2">{opp.service_fit_rationale}</p>
                            )}
                          </div>
                          <button
                            onClick={() => handleCreateService(opp.id)}
                            className="px-3 py-1.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm flex items-center gap-1"
                          >
                            <Settings className="w-4 h-4" />
                            Configure
                          </button>
                        </div>
                      </div>
                    )}
                    
                    {/* New Service Concept */}
                    {hasConcept && (
                      <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
                        <div className="flex items-start justify-between">
                          <div>
                            <h6 className="font-semibold text-purple-900 mb-1">New Service Concept</h6>
                            <p className="text-sm text-purple-800 font-medium">{opp.concept?.suggested_name}</p>
                            <p className="text-xs text-purple-700 mt-1">{opp.concept?.problem_it_solves}</p>
                            <p className="text-xs text-purple-600 mt-1">
                              Identified {opp.concept?.times_identified || 0} time(s)
                            </p>
                          </div>
                          <button
                            onClick={() => handleCreateService(opp.id, opp.concept?.id)}
                            className="px-3 py-1.5 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm flex items-center gap-1"
                          >
                            <Plus className="w-4 h-4" />
                            Create Service
                          </button>
                        </div>
                      </div>
                    )}
                    
                    {/* Adviser Tools */}
                    {(opp.talking_point || opp.question_to_ask || opp.quick_win) && (
                      <div className="space-y-2">
                        <h6 className="font-semibold text-gray-900 text-sm">Adviser Tools</h6>
                        
                        {opp.talking_point && (
                          <div className="bg-white border border-gray-200 rounded p-2">
                            <div className="flex items-start justify-between">
                              <div className="flex-1">
                                <p className="text-xs text-gray-500 mb-1">Talking Point</p>
                                <p className="text-sm text-gray-800">{opp.talking_point}</p>
                              </div>
                              <button
                                onClick={() => handleCopyTalkingPoint(opp.talking_point!, opp.id)}
                                className="ml-2 p-1.5 rounded hover:bg-gray-100 transition-colors"
                                title="Copy to clipboard"
                              >
                                {isCopied ? (
                                  <Check className="w-4 h-4 text-emerald-600" />
                                ) : (
                                  <Copy className="w-4 h-4 text-gray-600" />
                                )}
                              </button>
                            </div>
                          </div>
                        )}
                        
                        {opp.question_to_ask && (
                          <div className="bg-white border border-gray-200 rounded p-2">
                            <p className="text-xs text-gray-500 mb-1">Question to Ask</p>
                            <p className="text-sm text-gray-800">{opp.question_to_ask}</p>
                          </div>
                        )}
                        
                        {opp.quick_win && (
                          <div className="bg-white border border-gray-200 rounded p-2">
                            <p className="text-xs text-gray-500 mb-1">Quick Win</p>
                            <p className="text-sm text-gray-800">{opp.quick_win}</p>
                          </div>
                        )}
                      </div>
                    )}
                    
                    {/* Life Impact */}
                    {opp.life_impact && (
                      <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
                        <h6 className="font-semibold text-amber-900 text-sm mb-1">Life Impact</h6>
                        <p className="text-sm text-amber-800">{opp.life_impact}</p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ))}
    </div>

    {/* Create Service Modal */}
    {showCreateModal && createServiceData && (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
        <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-6">
          <h3 className="text-lg font-semibold mb-4">Create New Service</h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Service Name</label>
              <input
                type="text"
                value={createServiceData.name}
                onChange={(e) => setCreateServiceData({ ...createServiceData, name: e.target.value })}
                className="w-full px-3 py-2 border rounded-lg"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
              <textarea
                value={createServiceData.description}
                onChange={(e) => setCreateServiceData({ ...createServiceData, description: e.target.value })}
                rows={3}
                className="w-full px-3 py-2 border rounded-lg"
              />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Price (£)</label>
                <input
                  type="number"
                  value={createServiceData.suggestedPricing}
                  onChange={(e) => setCreateServiceData({ ...createServiceData, suggestedPricing: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                  placeholder="e.g. 2000"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Pricing Model</label>
                <select
                  value={createServiceData.pricingModel}
                  onChange={(e) => setCreateServiceData({ ...createServiceData, pricingModel: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                >
                  <option value="fixed">One-off</option>
                  <option value="month">Monthly</option>
                  <option value="annual">Annual</option>
                </select>
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
              <select
                value={createServiceData.category}
                onChange={(e) => setCreateServiceData({ ...createServiceData, category: e.target.value })}
                className="w-full px-3 py-2 border rounded-lg"
              >
                <option value="financial">Financial</option>
                <option value="operational">Operational</option>
                <option value="strategic">Strategic</option>
                <option value="personal">Personal</option>
                <option value="wealth">Wealth</option>
              </select>
            </div>
          </div>
          
          <div className="flex justify-end gap-3 mt-6">
            <button
              onClick={() => { setShowCreateModal(false); setCreateServiceData(null); }}
              className="px-4 py-2 text-gray-700 border rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              onClick={handleConfirmCreateService}
              disabled={creating || !createServiceData.name}
              className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 flex items-center gap-2"
            >
              {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
              Create Service
            </button>
          </div>
        </div>
      </div>
    )}
  </div>
  );
}
