-- Add missing columns to ma_insights table for AI-generated insights
-- These columns store additional insight metadata

-- Add data_points column (array of specific numbers backing the insight)
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS data_points TEXT[];

-- Add implications column (what this means for the business)
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS implications TEXT;

-- Add original_content column (stores original AI response for reference)
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS original_content JSONB;

-- Add recommendation_priority column if not exists
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS recommendation_priority VARCHAR(20);

-- Add priority column (critical, high, medium, low)
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS priority VARCHAR(20);

-- Add is_auto_generated column to track AI vs manual insights
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS is_auto_generated BOOLEAN DEFAULT FALSE;

-- Add status column for review workflow (draft, pending_review, approved, rejected)
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'draft';

-- Add show_to_client column
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS show_to_client BOOLEAN DEFAULT TRUE;

-- Add display_order column
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;

-- Add approval tracking columns
ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id);

ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ;

ALTER TABLE ma_insights
ADD COLUMN IF NOT EXISTS rejected_by UUID REFERENCES auth.users(id);

-- Create index on status for filtering
CREATE INDEX IF NOT EXISTS idx_ma_insights_status ON ma_insights(status);

-- Comment on new columns
COMMENT ON COLUMN ma_insights.data_points IS 'Array of specific data points backing this insight (e.g., ["£205,000 bank balance", "4.2 months runway"])';
COMMENT ON COLUMN ma_insights.implications IS 'Plain English explanation of what this insight means for the business';
COMMENT ON COLUMN ma_insights.original_content IS 'Original AI-generated content stored as JSON for reference';
COMMENT ON COLUMN ma_insights.is_auto_generated IS 'Whether this insight was generated by AI (true) or manually added (false)';
COMMENT ON COLUMN ma_insights.status IS 'Review workflow status: draft, pending_review, approved, rejected';
COMMENT ON COLUMN ma_insights.priority IS 'Insight priority: critical, high, medium, low';

